# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numofHours',
            field=models.TextField(null=True),
        ),
    ]
