# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_post_numofhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logIn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='logOut',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weekOfthemonth',
            field=models.TextField(null=True),
        ),
    ]
